FROM rust:1.80-slim as builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/{{PROJECT_NAME}} .
EXPOSE 8080
CMD ["./{{PROJECT_NAME}}"]
